ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"

[traps]

[traps.safe_wallet_trap]
path = "out/SafeTrap.sol/SafeTrap.json"
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1
private_trap = true

[traps.safe_wallet_trap.alert]
title = "Safe Wallet Event Detected"
severity = "medium"
enabled = true
labels = { "description" = "Safe Wallet Event Detected" }
alert_output_sig = "decodeAlertOutput" 
users = [{ address = "" }] # Replace with a real address
slack = { slack_channel = "#safe-wallet-alerts" } # Replace with your slack channel name
